<?php
session_start();
require "../dao/ProductoDao.php";
require "../dao/GrupoCategoriaDao.php";
require "../utils/Tools.php";

$grupoCategoriaDao = new GrupoCategoriaDao();
$conexion = (new Conexion())->getConexion();
$productoDao= new ProductoDao();
$tools = new Tools();

$dataConf = $tools->getConfiguracion();
$listaRamByCat = $productoDao->getDataRandonE();

$listaGrupos =$grupoCategoriaDao->getListaCate();
$listProdBan = $productoDao->getRandomInfo(1);
$palabra ="";
if (isset($_GET['search'])){
    $palabra =$_GET['search'];
}

$tipoPrecios = [
    'vp' => 'Precios VIP',
    'dt' => 'Precios DISTRIBUCI&Oacute;N'
];

$vh1 = isset($_GET['v']) && isset($tipoPrecios[$_GET['v']]) 
    ? $tipoPrecios[$_GET['v']]
    : '';

$vripo = $_GET['v'] ?? '';

$sql="SELECT cod_sub1 as codi_categoria, nom_sub1 as nombre FROM sopsub1 WHERE cod_sub1 != '000' ORDER BY cod_sub1";
$listaGrupos = $conexion->query($sql);
?><!DOCTYPE html>
<?php include '../fragment/head_general.php'?>
    <!-- SITE TITLE -->
    <title>COMPUTER</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="../public/favi.png">
<!-- Animation CSS -->
<link rel="stylesheet" href="../public/assets/css/animate.css">	
<!-- Latest Bootstrap min CSS -->
<link rel="stylesheet" href="../public/assets/bootstrap/css/bootstrap.min.css">
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800,900&display=swap" rel="stylesheet"> 
<!-- Icon Font CSS -->
<link rel="stylesheet" href="../public/assets/css/all.min.css">
<link rel="stylesheet" href="../public/assets/css/ionicons.min.css">
<link rel="stylesheet" href="../public/assets/css/themify-icons.css">
<link rel="stylesheet" href="../public/assets/css/linearicons.css">
<link rel="stylesheet" href="../public/assets/css/flaticon.css">
<link rel="stylesheet" href="../public/assets/css/simple-line-icons.css">
<!--- owl carousel CSS-->
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.carousel.min.css">
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.theme.css">
<link rel="stylesheet" href="../public/assets/owlcarousel/css/owl.theme.default.min.css">
<!-- Magnific Popup CSS -->
<link rel="stylesheet" href="../public/assets/css/magnific-popup.css">
<!-- jquery-ui CSS -->
<link rel="stylesheet" href="../public/assets/css/jquery-ui.css">
<!-- Slick CSS -->
<link rel="stylesheet" href="../public/assets/css/slick.css">
<link rel="stylesheet" href="../public/assets/css/slick-theme.css">
<!-- Style CSS -->
<link rel="stylesheet" href="../public/assets/css/style.css">
<link rel="stylesheet" href="../public/assets/css/responsive.css">
    <link rel="stylesheet" href="../public/plugin/sweetalert2/sweetalert2.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <style>
        .float{
            padding-top: 7px;
            position:fixed;
            width:60px;
            height:60px;
            bottom:40px;
            right:80px;
            background-color:#25d366;
            color:#FFF;
            border-radius:50px;
            text-align:center;
            font-size:30px;
            box-shadow: 2px 2px 3px #999;
            z-index:100;
        }

    </style>
<style type="text/css">
    #loader-pre-prod{
        display: block;
        position: absolute;
        z-index: 500;
        background-color: #ffffffb8;
        width: 100%;
        height: 100%;
        display:flex;
        justify-content: center;
        align-items: center;
    }
    @keyframes ldio-tsbmxkn5l7n {
        0% { transform: translate(-50%,-50%) rotate(0deg); }
        100% { transform: translate(-50%,-50%) rotate(360deg); }
    }
    .ldio-tsbmxkn5l7n div {
        position: absolute;
        width: 120px;
        height: 120px;
        border: 20px solid #ff3d57;
        border-top-color: transparent;
        border-radius: 50%;
    }
    .ldio-tsbmxkn5l7n div {
        animation: ldio-tsbmxkn5l7n 1s linear infinite;
        top: 100px;
        left: 100px
    }
    .loadingio-spinner-rolling-ox3sfpgdu8h {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }
    .ldio-tsbmxkn5l7n {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-tsbmxkn5l7n div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>
<style>
    .on-click-cont:hover{
        cursor: pointer;
    }
</style>
</head>

<body>

<!-- LOADER -->
<div class="preloader">
    <div class="lds-ellipsis">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!-- END LOADER -->

<!-- End Screen Load Popup Section --> 

<!-- START HEADER -->
<?php include "../fragment/head_secon.php";?>
<!-- END HEADER -->

<!-- START SECTION BREADCRUMB -->
<div class="breadcrumb_section bg_gray page-title-mini"  style="padding-bottom: 20px;padding-top: 20px;">
    <div class="container"><!-- STRART CONTAINER -->
        <div class="row align-items-center">
        	<div class="col-md-6">
                <div class="page-title">
            		<h1>Productos <?=$vh1?></h1>
                </div>
            </div>
            <div class="col-md-6">
                <ol class="breadcrumb justify-content-md-end">
                    <li hidden class="breadcrumb-item"><a href="#">Inicio</a></li>
                    <li hidden class="breadcrumb-item"><a href="#">Pagina</a></li>
                    <li style="font-size: 18px;color: #232323">TC: <span style="color: white">-</span> <strong><?=$tc?></strong></li>
                </ol>
            </div>
        </div>
    </div><!-- END CONTAINER-->
</div>
<!-- END SECTION BREADCRUMB -->

<!-- START MAIN CONTENT -->
<div class="main_content">

<!-- START SECTION SHOP -->
<div class="section" style="padding-top: 29px;">

    <input value="<?=$palabra?>" id="palabra" type="hidden">
     
    <div class="custom-container">
        <!--<div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <form action="shop-list-prod.php" method="GET" style="padding-bottom: 20px;display: block;margin: auto;" class="col-md-12">
                    <input value="<?=$vripo?>" name="v" id="flista" type="hidden"> 
                    <div class="search-container">
                        <input class="rounded-left-input" name="search" placeholder="Buscar producto" required="" type="text">
                        <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
                    </div>                
		    </form>
            </div>
        </div>-->
    	<div class="row">
		<div class="col-lg-12" id="content_principal">
	         <div class="row mb-4">
		    
		    <div class="col-md-4">
			    <div class="custom_select">
                           <select class="form-control form-control-sm" @change="changePrecio($event)">
                              <option value="">Ordenar por</option>
                              <option value="asc">Precio: del m&aacute;s bajo al m&aacute;s alto</option>
                              <option value="desc">Precio: del m&aacute;s alto al m&aacute;s bajo</option>
                           </select>
                       </div>
		    </div>
		   <div class="col-md-4">
			   <div class="custom_select">
                           <select class="form-control form-control-sm" id="catFIL" @change="changeCatfil($event)">
                              <option value="">Filtrar por Categoria:</option>
                              <?php
                            $contadorCCc = 0;
                            foreach ($listaGrupos as $catRow){
					echo '<option value='.$catRow['codi_categoria'].'>'.$catRow['nombre'].'</option>';
				                            
				    }
                            ?>

                           </select>
                       </div>

		   </div>
		   <div class="col-md-4">
  			  <div class="search-container">
                        <input class="form-control form-control-sm" name="filtroPal" v-model="filtroPal" @input="changePal($event)" placeholder="Buscar por nombre " required="" type="text">
                        
                    </div>  
		   </div>
		 </div>


                <div class="row shop_container grid">
                    <div id="loader-pre-prod">
                            <div class="loadingio-spinner-rolling-ox3sfpgdu8h">
                                <div class="ldio-tsbmxkn5l7n">
                                    <div></div>
                                </div>
                           </div>
                    </div>

			
                <div class="table-responsive shop_cart_table">
                	<table class="table">
                    	<thead>
                        	<tr>
                            	<th class="product-thumbnail">IMAGEN</th>
                                <th class="product-name">PRODUCTO</th>
                                <th class="product-name">SUB1</th>
                                <th class="product-name">SUB2</th>
                                <th class="product-name">SUB3</th>
					  <th class="product-name">LIMA</th>
					  <th class="product-name">TOTAL</th>
                                <th class="product-name">PRECIO</th>
					  <th class="product-name text-center">AGREGAR</th>
                            </tr>
                        </thead>
                        <tbody>
                        	<tr  v-for="(item, index) in listaHoja">
                            	<td class="product-thumbnail"><a href="#"> <img :src="'../public/img/productos/'+item.imagen1" :alt="item.nombre"></a></td>
                              <td class="text-left">{{item.nombre}}
					  <div class="pr_desc">
                                    <p>* {{item.content1}}</p>
                                    <p>* {{item.content2}}</p>
                                    <p>* {{item.content3}}</p>
                                </div>
					</td>
                              <td>0</td>
                              <td>0</td>
                              <td>0</td>
					<td><span v-if="formartNumberStock(item.stock)==0" style="font-weight: lighter;color: #d70000"> Sin Stock</span>
                                                <span v-if="formartNumberStock(item.stock)<=10&&formartNumberStock(item.stock)>0" style="font-weight: lighter;color: #03ad01"> {{formartNumberStock(item.stock)}}</span>
                                                <span v-if="formartNumberStock(item.stock)>10" style="font-weight: lighter;color: #03ad01">+10</span></td>
					<td><span v-if="formartNumberStock(item.stock)==0" style="font-weight: lighter;color: #d70000"> Sin Stock</span>
                                                <span v-if="formartNumberStock(item.stock)<=10&&formartNumberStock(item.stock)>0" style="font-weight: lighter;color: #03ad01"> {{formartNumberStock(item.stock)}}</span>
                                                <span v-if="formartNumberStock(item.stock)>10" style="font-weight: lighter;color: #03ad01">+10</span></td>
					<td> <span class=""><strong>S/. {{getCamBio(item.precio)}}</strong></span></td>
					  <td class="product-quantity" data-title="Cantidad"><div class="quantity">
                                <input type="button" v-on:click="min(index)" style="background-color: black; color: white; border: none; cursor: pointer;"  value="-" class="minus">
                                <input type="text" disabled name="quantity" v-model="item.inistock" title="Qty" class="qty" size="1">
                                <input type="button" v-on:click="sum(index)" style="background-color: black; color: white; border: none; cursor: pointer;"  value="+" class="plus">
                              </div></td>
                            </tr>

                        </tbody>
                        
                    </table>
                </div>

           



                </div>
                <div class="row">
                    <div class="col-12">
                        <div id="example" style="margin: auto;display: block;"></div>
                
                    </div>
                </div>


	 </div>
    </div>
  </div>
</div>

<!-- END SECTION SHOP -->

<!-- START SECTION SUBSCRIBE NEWSLETTER -->
   <?php require_once "../fragment/plantilla_suscribete.php"?>
<!-- START SECTION SUBSCRIBE NEWSLETTER -->

</div>


<!-- END MAIN CONTENT -->

<!-- START FOOTER -->
<?php include "../fragment/footer_gen.php"?>
<!-- END FOOTER -->

<a href="#" class="scrollup" style="display: none;"><i class="ion-ios-arrow-up"></i></a> 

<!-- Latest jQuery --> 
<script src="../public/assets/js/jquery-1.12.4.min.js"></script>
<script>
    $(".preloader").hide()
</script>
<!-- jquery-ui --> 
<script src="../public/assets/js/jquery-ui.js"></script>
<!-- popper min js -->
<script src="../public/assets/js/popper.min.js"></script>
<!-- Latest compiled and minified Bootstrap --> 
<script src="../public/assets/bootstrap/js/bootstrap.min.js"></script> 
<!-- owl-carousel min js  --> 
<script src="../public/assets/owlcarousel/js/owl.carousel.min.js"></script> 
<!-- magnific-popup min js  --> 
<script src="../public/assets/js/magnific-popup.min.js"></script> 
<!-- waypoints min js  --> 
<script src="../public/assets/js/waypoints.min.js"></script> 
<!-- parallax js  --> 
<script src="../public/assets/js/parallax.js"></script> 
<!-- countdown js  --> 
<script src="../public/assets/js/jquery.countdown.min.js"></script> 
<!-- imagesloaded js --> 
<script src="../public/assets/js/imagesloaded.pkgd.min.js"></script>
<!-- isotope min js --> 
<script src="../public/assets/js/isotope.min.js"></script>
<!-- jquery.dd.min js -->
<script src="../public/assets/js/jquery.dd.min.js"></script>
<!-- slick js -->
<script src="../public/assets/js/slick.min.js"></script>
<!-- elevatezoom js -->
<script src="../public/assets/js/jquery.elevatezoom.js"></script>
<!-- scripts js-->
<script src="../public/assets/js/scripts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>
<script src="../public/js/tools.js"></script>
<script src="../public/js/main.js?v=8"></script>
<script src="../public/plugin/sweetalert2/vue-swal.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="../public/js/bootstrap-paginator.js"></script>

</body>

<script type='text/javascript'>

    var options = {
        currentPage: 1,
        totalPages: 2,
        alignment:'center',
        shouldShowPage:function(type, page, current){
            switch(type)
            {
                case "first":
                case "last":
                    return false;
                default:
                    return true;
            }
        },
        onPageClicked: function(e,originalEvent,type,page){
            APP_PROD.setNumHoja(page)

        }
    }
    var pagPaginador
    $(document).ready(function (){

        $('#example').bootstrapPaginator(options);
    })
</script>
<script>

    $("#loader-pre-prod").hide();

    var $container22;
    const APP_PROD = new Vue({
        el:"#content_principal",
        data:{
            valueUSDMin:0,
            valueUSDMax:5000,
            palabra:'',
            listaProdGene:[],
            listaBusquedaE:[],
            listaMarcar:[],
            listaHoja:[],
		listaHojaOR:[],
            cntPorHoja:0,
            cntItemPorHoja:12,
            cntHojas:0,
            hojaActual:1,
            cantidadProd:0,
            lasrId:0,
            listaMarcaFiltro:[],
            tc:1,
	      flista:'',
		filtroPal:'',
		listaCarrito:[], 
		categoriaf:''

        },
        methods:{
		min(index){
			const  prod = this.listaHoja[index];
			if (prod.inistock<2) {
			prod.inistock--; 
			CARRITO.eliminarProdCarrito(prod);
			} else {
				//alert('restar 1');
				CARRITO.eliminarProdCarr(prod);
				prod.inistock--; 
			}
            }
	     , 
		sum(index){
		
		    const  prod = this.listaHoja[index];
		    prod.inistock++;   
                CARRITO.setCarrito(prod);
		        
		}
		,
	     changePal(event) { 
            this.filtroPal = event.target.value;
		
		if (!this.filtroPal.trim()) {
		        return this.listaHoja;
      	}
	
		 this.categoriaf = $('#catFIL').val();
      	 ///this.flista = $('#flista').val();
		 const vue = this
                const dataS={
                    tipo:'pag-search2PD',pal:this.filtroPal,
                    forma:"<?=(isset($_GET['type'])&&strlen($_GET['type'])>0)?$_GET['type']:'all'?>",
                    cntPH:this.cntItemPorHoja,
                    hojaActual:this.hojaActual-1,
                    minUSD:this.valueUSDMin,
                    maxUSD:this.valueUSDMax,
                    marcasFilt:JSON.stringify(this.listaMarcaFiltro),
		        filtro: this.categoriaf 			
                }

                $("#loader-pre-prod").show();
                $(".scrollup").click()
                $.ajax({
                    type: "POST",
                    data: dataS,
                    url: "../ajax/ajs_productos.php",
                    success: function (resp){
                        $("#loader-pre-prod").hide()
                        //console.log(resp);
                        const listaPro=JSON.parse(resp)
                        console.log(listaPro);
                        vue.listaHoja = listaPro.datas
				vue.listaHojaOR = listaPro.datas
                        listaPro.cnt = Math.ceil(listaPro.cnt/vue.cntItemPorHoja)
                        if (options.totalPages!=listaPro.cnt){
                            options.totalPages=listaPro.cnt
                            $('#example').bootstrapPaginator(options);

                        }

                    }
                })

	       
   	    },	
           changeCatfil(event) { 
	      //console.log(event.target.value);
		this.categoriaf = $('#catFIL').val();

		const vue = this
                const dataS={
                    tipo:'pag-search2PD',pal:this.filtroPal,
                    forma:"<?=(isset($_GET['type'])&&strlen($_GET['type'])>0)?$_GET['type']:'all'?>",
                    cntPH:this.cntItemPorHoja,
                    hojaActual:this.hojaActual-1,
                    minUSD:this.valueUSDMin,
                    maxUSD:this.valueUSDMax,
                    marcasFilt:JSON.stringify(this.listaMarcaFiltro),
		        filtro: this.categoriaf 			
                }

                $("#loader-pre-prod").show();
                $(".scrollup").click()
                $.ajax({
                    type: "POST",
                    data: dataS,
                    url: "../ajax/ajs_productos.php",
                    success: function (resp){
                        $("#loader-pre-prod").hide()
                        //console.log(resp);
                        const listaPro=JSON.parse(resp)
                        console.log(listaPro);
                        vue.listaHoja = listaPro.datas
				vue.listaHojaOR = listaPro.datas
                        listaPro.cnt = Math.ceil(listaPro.cnt/vue.cntItemPorHoja)
                        if (options.totalPages!=listaPro.cnt){
                            options.totalPages=listaPro.cnt
                            $('#example').bootstrapPaginator(options);

                        }

                    }
                })


                 
   	    },
	     changePrecio(event) { 
	      this.ordenpres = event.target.value;
            this.listaHoja = [...this.listaHoja].sort((a, b) => {
             if (this.ordenpres === 'asc') {
               return a.precio - b.precio;
             } 
            if (this.ordenpres === 'desc') {
            return b.precio - a.precio;
             }
           });
   	   },	
            getCamBio(precio){
                return (parseFloat(precio)*1).toFixed(2);
            },
            establecerTC(){
                this.tc = parseFloat($("#tasa_cambio").val());
            },
            formartNumberStock(num){
                return parseInt(num+"");
            },
            agregarFiltroMarca(mar){
                this.listaMarcaFiltro.push(mar)
            },
            eliminarFiltroMarca(mar){
                var index = this.listaMarcaFiltro.indexOf(mar);
                this.listaMarcaFiltro.splice(index, 1);
            },
            getMArcasFiltro(){
                const vue = this
                $.ajax({
                    type: "POST",
                    data: { tipo:'pag-search2PMarcas',pal: APP_PROD._data.palabra},
                    url: "../ajax/ajs_productos.php",
                    success: function (resp) {
                        resp=JSON.parse(resp);
                        console.log(resp);
                        vue.listaMarcar=resp;
                        vue.setListaMarcas()
                    }
                })
            },
            setListaMarcas(){
                /*this.listaMarcar=[];
                for (var i=1;i<this.listaProdGene.length;i++){
                    this.listaMarcar.push(this.listaProdGene[i].marca);
                }
                this.listaMarcar = this.listaMarcar.filter(function (value, index, self) {
                    return self.indexOf(value) === index;
                })*/

                this.listaMarcar.forEach(function (item,index) {
                    $("#listaMarcas").append('<li>\n' +
                        '                                <div class="custome-checkbox">\n' +
                        '                                    <input class="form-check-input input-check-marc" type="checkbox" name="'+item.cod+'" id="'+item.cod+'" value="'+item.cod+'">\n' +
                        '                                    <label class="form-check-label" for="'+item.cod+'"><span>'+item.nombre+'</span></label>\n' +
                        '                                </div>\n' +
                        '                            </li>');
                })
            },
            getFiltrar(){
                this.valueUSDMin = parseFloat( $("#price_first").val());
                this.valueUSDMax = parseFloat($("#price_second").val());
                this.paginadorListaServer()
            },
            paginadorListaServer(){
		
		 this.categoriaf = $('#catFIL').val();
		 const vue = this
                const dataS={
                    tipo:'pag-search2PD',pal:APP_PROD._data.palabra,
                    forma:"<?=(isset($_GET['type'])&&strlen($_GET['type'])>0)?$_GET['type']:'all'?>",
                    cntPH:this.cntItemPorHoja,
                    hojaActual:this.hojaActual-1,
                    minUSD:this.valueUSDMin,
                    maxUSD:this.valueUSDMax,
                    marcasFilt:JSON.stringify(this.listaMarcaFiltro),
		        filtro: this.categoriaf 			
                }

                $("#loader-pre-prod").show();
                $(".scrollup").click()
                $.ajax({
                    type: "POST",
                    data: dataS,
                    url: "../ajax/ajs_productos.php",
                    success: function (resp){
                        $("#loader-pre-prod").hide()
                        //console.log(resp);
                        const listaPro=JSON.parse(resp)
                        console.log(listaPro);
                        vue.listaHoja = listaPro.datas
				vue.listaHojaOR = listaPro.datas
                        listaPro.cnt = Math.ceil(listaPro.cnt/vue.cntItemPorHoja)
                        if (options.totalPages!=listaPro.cnt){
                            options.totalPages=listaPro.cnt
                            $('#example').bootstrapPaginator(options);

                        }

                    }
                })
            },
            getDataProdListaPag2(){
                /*const cnt = this.cntItemPorHoja;
                const min = this.lasrId;
                console.log(APP_PROD._data.palabra);
                $.ajax({
                    type: "POST",
                    url: "../ajax/ajs_productos.php",
                    data: {tipo:'pag-search2',pal:APP_PROD._data.palabra,
                        forma:"<?=(isset($_GET['type'])||strlen($_GET['type'])>0)?$_GET['type']:'all'?>",

                    },
                    success: function (resq) {
                         
                        resq= JSON.parse(resq);
                        //console.log(resq);
                        //resq = resq.reverse();
                       // APP_PROD._data.listaHoja= resq
                        APP_PROD._data.listaProdGene= resq
                        APP_PROD._data.listaBusquedaE= resq
                        APP_PROD.getPreparePagination2();
                        APP_PROD.setListaMarcas();
                         console.log('lista');
                        $(".scrollup").click()
                    }
                });*/

            },
            resetFiter(){
                this.listaBusquedaE=[];
                for (var i=0;i<this.listaProdGene.length;i++){
                    const precioProd =parseFloat(this.listaProdGene[i].precio+"");
                    if (precioProd>=this.valueUSDMin && precioProd<=this.valueUSDMax){
                        if (this.listaMarcaFiltro.length>0){

                            if (this.listaMarcaFiltro.indexOf(this.listaProdGene[i].marca)!=-1){
                                if (en_stock_filtro){
                                    if (parseFloat(this.listaProdGene[i].stock)>0){
                                        this.listaBusquedaE.push(this.listaProdGene[i]);
                                    }
                                }else{
                                    this.listaBusquedaE.push(this.listaProdGene[i]);
                                }
                            }

                        }else{
                            if (en_stock_filtro){
                                if (parseFloat(this.listaProdGene[i].stock)>0){
                                    this.listaBusquedaE.push(this.listaProdGene[i]);
                                }
                            }else{
                                this.listaBusquedaE.push(this.listaProdGene[i]);
                            }
                        }

                    }
                }
                this.getPreparePagination2();

            },
            getPreparePagination2(){
                console.log("aaaaaaaaaa")
                this.paginadorListaServer()
                /*this.cntHojas = Math.ceil(this.listaBusquedaE.length/this.cntItemPorHoja);
                options.totalPages=this.cntHojas
                $('#example').bootstrapPaginator(options);
                this.viewDataHojaSc();*/
            },
            viewDataHojaSc(){
                this.listaHoja=[];
                //this.numCntHojas = Math.ceil(this.listaProductos.length/this.itemMaximo);
                for (var i=(this.hojaActual-1)*this.cntItemPorHoja; i < this.cntItemPorHoja * this.hojaActual; i++ ){
                    if (i<this.listaBusquedaE.length){
                        this.listaHoja.push(this.listaBusquedaE[i]);
                    }else{
                        break;
                    }
                }
               // $(".scrollup").click()
            },

            agregarCarritoProd(index){
                //swal('Opción no habilitada',"","warning")
                const  prod = this.listaHoja[index];
                //console.log(this.listaHoja[index])
                CARRITO.setCarrito(prod);

            },
            formatNumerPrecio(num){
                return parseFloat(num+"").toFixed(2)
            },
            getPreparePagination(){
                this.cntHojas = Math.ceil(this.cantidadProd/this.cntItemPorHoja);
                this.getDataProdListaPag();
            },
            setNumHoja(num){
                this.hojaActual=num;
                //this.viewDataHojaSc();
                this.paginadorListaServer();
                /*if (this.hojaActual==1){
                    this.lasrId=0;
                }else{
                    this.lasrId = this.listaHoja[this.listaHoja.length-1].prod_id
                }

                this.getDataProdListaPag();*/
            },
            setSwithHoja(num){
                console.log(num);

                if ( this.hojaActual+num > 0&& this.hojaActual+num <= this.cntHojas){
                    this.hojaActual+=num;
                    /*if (this.hojaActual==1){
                        this.lasrId=0;
                    }else{
                        this.lasrId = this.listaHoja[this.listaHoja.length-1].prod_id
                    }*/
                    this.viewDataHojaSc();

                    //this.getDataProdListaPag();
                }

            },
            getDataProdListaPag(){
                const cnt = this.cntItemPorHoja;
                const min = this.lasrId;
                $.ajax({
                    type: "POST",
                    url: "../ajax/ajs_productos.php",
                    data: {tipo:'pag-search',cnt,min,pal:APP_PROD._data.palabra},
                    success: function (resq) {
                       // console.log(resq);
                        resq= JSON.parse(resq);
                        APP_PROD._data.listaHoja= resq
                       // console.log(resq);
                       console.log(resp);
                        $(".scrollup").click()
                    }
                });

            },

            getDataCountProd(){
                $.ajax({
                    type: "POST",
                    url: "../ajax/ajs_productos.php",
                    data: {tipo:'pag-search-count',pal:APP_PROD._data.palabra},
                    success: function (resp) {
                        if (isJson(resp)){
                            resp=JSON.parse(resp);
                            if (resp.res){
                                APP_PROD._data.cantidadProd = parseInt(resp.cnt);
                                APP_PROD.getPreparePagination();
                            }else {

                            }
                        }else{

                        }
                        console.log(resp)
                    }
                });

            }
        },
        computed:{
            getPagNum(){
                var numero =[];
                for (var i =1 ; i<= this.cntHojas;i++){
                    numero.push(i);
                }
                console.log(numero)
                return numero;
            },

        }
    });

    var en_stock_filtro=false
    $( document ).ready(function() {
        $("#en-stock").change(function() {
            en_stock_filtro=this.checked;
            APP_PROD.resetFiter();
        });
        APP_PROD.establecerTC();
        APP_PROD._data.palabra=$("#palabra").val();
        APP_PROD.paginadorListaServer()
        //APP_PROD.getDataProdListaPag2()
        APP_PROD.getMArcasFiltro()

        $('#price_first').on('input',function(e){
            console.log("assss")
            APP_PROD.getFiltrar();
        });

        setTimeout(function () {
            $( '.main_content' ).on( 'click',".input-check-marc", function() {
                if( $(this).is(':checked') ){
                    // Hacer algo si el checkbox ha sido seleccionado
                    APP_PROD.agregarFiltroMarca($(this).val());
                } else {
                    // Hacer algo si el checkbox ha sido deseleccionado
                    APP_PROD.eliminarFiltroMarca($(this).val());
                }
                APP_PROD.resetFiter();
            });
        },1500)

        //APP_PROD.getDataCountProd()

        /*setTimeout(function () {
            $('.shorting_icon').on('click',function() {
                if ($(this).hasClass('grid')) {
                    $('.shop_container').removeClass('list').addClass('grid');
                    $(this).addClass('active').siblings().removeClass('active');
                }
                else if($(this).hasClass('list')) {
                    $('.shop_container').removeClass('grid').addClass('list');
                    $(this).addClass('active').siblings().removeClass('active');
                }
                $(".shop_container").append('<div class="loading_pr"><div class="mfp-preloader"></div></div>');
                setTimeout(function(){
                    $('.loading_pr').remove();
                    $container.isotope('layout');
                }, 800);
            });
        })*/
    });
</script>
</html>