ALTER TABLE clientes ADD COLUMN departamento VARCHAR(100) DEFAULT NULL;
ALTER TABLE clientes ADD COLUMN provincia VARCHAR(100) DEFAULT NULL;
ALTER TABLE clientes ADD COLUMN distrito VARCHAR(100) DEFAULT NULL;
ALTER TABLE clientes ADD COLUMN fecha_nacimiento DATE DEFAULT NULL;
